apiVersion: apps/v1
kind: StatefulSet
metadata:
  name:  {{ include "heimdall.fullname" . }}
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
    app.kubernetes.io/component: heimdall
spec:
  serviceName: {{ template "heimdall.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "heimdall.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: heimdall
  template:
    metadata:
      {{- with .Values.heimdall.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "heimdall.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: heimdall
    spec:
      {{- with .Values.heimdall.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.heimdall.podSecurityContext | nindent 8 }}
      containers:
        - name: heimdall-front
          securityContext:
            {{- toYaml .Values.heimdall.securityContext | nindent 12 }}
          image: "{{ .Values.heimdall.image.repository }}:{{ .Values.heimdall.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.heimdall.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: NODE_ENV
              value: {{ .Values.nodeEnv | quote }}
            - name: DATABASE_HOST
            {{- if .Values.postgresql.enabled }}
              value: {{ template "heimdall.fullname" . }}-postgresql
            {{- else }}
              value: {{.Values.databaseHost | quote }}
            {{- end }}
            - name: DATABASE_PORT
            {{- if .Values.postgresql.enabled }}
              value: {{ .Values.postgresql.service.port | quote }}
            {{- else }}
              value: {{.Values.databasePort | quote }}
            {{- end }}           
            - name: POSTGRES_DB
              value: {{ .Values.databaseName | quote }}
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "heimdall.fullname" . }}
                  key: databaseUsername
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "heimdall.fullname" . }}
                  key: databasePassword
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "heimdall.fullname" . }}
                  key: jwtSecret
            - name: JWT_TIMEOUT
              value: {{ .Values.jwtTimeout | quote }}
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 15
            failureThreshold: 3
      {{- with .Values.heimdall.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.heimdall.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.heimdall.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
